### ISSUE TITLE
Is a Pi function supported?

### ISSUE THREAD

**Issue by rgleason** [RooieDirk/NmeaConverter_pi#12]
This question came up from Rhythm Dr.  It doesn't seem to be in the documentation.

**Comment by RooieDirk** [comment]
No it isn't, but for normal calculation a value of 3,14 would give you about 0.5 degrees error.
To be save 3.1416 would be more then enough.
I saw that in the library used for calculating there is now an option to use degrees instead of radians. For the next version I could add an option for this, then the pi() wouldn't be needed any more.

**Comment by rgleason** [comment]
Sounds like that might be a good idea.

**Comment by rgleason** [comment]
Thanks
